stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "--batch-mode"

build:
  stage: build
  script:
    - mvn $MAVEN_CLI_OPTS clean package

test:
  stage: test
  script:
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  script:
    - echo "Deploy to production server here" # Thay thế lệnh này bằng các bước triển khai thực tế
  only:
    - master # Chỉ triển khai từ nhánh master
