stages:
  - deploy

deploy:
  image: centos:latest
  stage: deploy
  only:
    - master
  before_script:
    - yum -y update  # Thay đổi lệnh để cập nhật trên CentOS
    - yum -y install openssh  # Thay đổi lệnh để cài đặt openssh trên CentOS
    - install -m 600 -D /dev/null ~/.ssh/id_rsa
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_rsa
    - ssh-keyscan -H $SSH_HOST > ~/.ssh/known_hosts  # Sửa đổi tên tệp để đúng cú pháp và đường dẫn
  script:
    - ssh $SSH_USER@$SSH_HOST "cd $WORK_DIR && git checkout $MAIN_BRANCH && git pull && exit"
  after_script:
    - rm -rf ~/.ssh
