stages:
  - build
  - deploy

variables:
  IMAGE_NAME: quanly
  CONTAINER_NAME: quanly

build:
  stage: build
  script:
    - mvn clean install
    - docker build -t $IMAGE_NAME:$CI_COMMIT_REF_NAME .

deploy:
  stage: deploy
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
    - docker stop $CONTAINER_NAME || true
    - docker rm $CONTAINER_NAME || true
    - docker run -d -p 8080:8080 --name $CONTAINER_NAME $IMAGE_NAME:$CI_COMMIT_REF_NAME
