stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t quanly:tag .
  only:
    - master

deploy:
  stage: deploy
  script:
    - docker run -d -p 8080:8080 quanly:tag
  only:
    - master
