stages:
  - build
  - deploy

build:
  stage: build
  script:
    - ./mvnw clean package

deploy:
  stage: deploy
  only:
    - master
  script:
    - scp target/your-app.jar root@y103.163.119.189:/path/to/deployment/directory
    - ssh root@y103.163.119.189'sudo systemctl restart your-app.service'
