stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker build -t my-java-app .

deploy:
  stage: deploy
  only:
    - master  # Chỉ triển khai từ nhánh master
  script:
    - docker run -d --name my-java-app my-java-app

before_script:
  - docker info
  - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" "$CI_REGISTRY"
