CREATE TABLE NHA
(
    ID             SERIAL PRIMARY KEY,
    MA_NHA         VARCHAR(1000),
    TINH_TRANG_NHA VARCHAR(20),
    DIA_CHI        VARCHAR(500),
    GIA_THUE       DECIMAL,
    DIEN_TICH      DECIMAL,
    HINH_ANH       TEXT,
    TONG_SO_TANG   INTEGER,
    LOAI_NHA       VARCHAR(20),
    GHI_CHU        VARCHAR(1000),
    NGUOI_TAO      VARCHAR(4000),
    NGAY_TAO       TIMESTAMP,
    NGUOI_SUA      VARCHAR(4000),
    NGAY_SUA       TIMESTAMP,
    IS_DELETE      SMALLINT
);