CREATE TABLE SO_LUONG(
    ID BIGINT PRIMARY KEY,
    ID_SAN_PHAM BIGINT,
    ID_EVENT BIGINT,
    SO_LUONG_TONG BIGINT,
    SO_LUONG_TON BIGINT,
    SO_LUONG_TREO BIGINT,
    ID_GIO_HANG BIGINT,
    TRANG_THAI int4

);