CREATE TABLE THANH_TOAN
(
    ID        SERIAL PRIMARY KEY,
    SO_TIEN   DECIMAL,
    GHI_CHU   VARCHAR(1000),
    NGUOI_TAO VARCHAR(4000),
    NGAY_TAO  TIMESTAMP,
    NGUOI_SUA VARCHAR(4000),
    NGAY_SUA  TIMESTAMP,
    ID_DICH_VU INTEGER,
    ID_HOP_DONG INTEGER,
    IS_DELETE SMALLINT
);