ALTER TABLE PHONG_TRO
    ADD COLUMN ID_KHACH_THUE INTEGER;

ALTER TABLE NHA
    ADD COLUMN ID_KHACH_THUE INTEGER;

ALTER TABLE PHONG_TRO
    ADD CONSTRAINT KHACH_THUE_PHONG_TR0 FOREIGN KEY (ID_KHACH_THUE)
        REFERENCES khach_thue (ID);

ALTER TABLE NHA
    ADD CONSTRAINT KHACH_THUE_NHA FOREIGN KEY (ID_KHACH_THUE)
        REFERENCES khach_thue (ID);

ALTER TABLE lich_su_dich_vu
    ADD COLUMN ID_THANH_TOAN INTEGER;

ALTER TABLE lich_su_dich_vu
    ADD CONSTRAINT LICH_SU_DICH_VU_THANH_TOAN FOREIGN KEY (ID_THANH_TOAN)
        REFERENCES thanh_toan (ID);