ALTER TABLE THANH_TOAN
    ADD CONSTRAINT  THANH_TOAN_DICH_VU FOREIGN KEY (id_dich_vu)
        REFERENCES DICH_VU (ID);


ALTER TABLE THANH_TOAN
    ADD CONSTRAINT  THANH_TOAN_HOP_DONG FOREIGN KEY (id_hop_dong)
        REFERENCES hop_dong (ID);