CREATE OR REPLACE FUNCTION set_manha()
RETURNS TRIGGER AS $$
BEGIN
    NEW.MA_NHA := 'NH' || NEW.id::TEXT;
RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trigger_set_manha
    BEFORE INSERT ON NHA
    FOR EACH ROW
EXECUTE FUNCTION set_manha();