CREATE TABLE DICH_VU
(
    ID          SERIAL PRIMARY KEY,
    MA_DICH_VU  VARCHAR,
    TEN_DICH_VU VARCHAR(100),
    GIA         DECIMAL,
    MO_TA       TEXT,
    DVT         VARCHAR,
    NGUOI_TAO   VARCHAR(4000),
    NGAY_TAO    TIMESTAMP,
    NGUOI_SUA   VARCHAR(4000),
    NGAY_SUA    TIMESTAMP,
    IS_DELETE   SMALLINT
);