CREATE TABLE PHONG_TRO
(
    ID                SERIAL PRIMARY KEY,
    MA_PHONG          VARCHAR(255),
    TINH_TRANG_PHONG  VARCHAR(20),
    GIA_THUE          DECIMAL,
    DIEN_TICH         DECIMAL,
    HINH_ANH          TEXT,
    DIA_CHI           VARCHAR(500),
    SO_TANG           VARCHAR(100),
    LOAI_PHONG        VARCHAR(20),
    SO_NGUOI_TOI_DA   SMALLINT,
    SO_NGUOI_HIEN_TAI SMALLINT,
    NGAY_SAN_SANG     TIMESTAMP,
    NGUOI_TAO         VARCHAR(255),
    NGAY_TAO          TIMESTAMP,
    NGUOI_SUA         VARCHAR(255),
    NGAY_SUA          TIMESTAMP,
    IS_DELETE         SMALLINT

);