name: Build, Run, and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build_run_and_push:
    runs-on: centos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          echo "DOCKER_HOST=$DOCKER_HOST" >> $GITHUB_ENV
          sudo yum install -y docker
          sudo systemctl start docker
          sudo systemctl enable docker

      - name: Build Docker image
        run: |
          docker build -t your-docker-image-name:latest .

      - name: Run Docker container with port mapping
        run: |
          docker run -d -p 8080:8080 --name your-container-name your-docker-image-name:latest

      - name: Tag Docker image for registry
        run: |
          docker tag your-docker-image-name:latest $DOCKER_HOST/your-docker-image-name:latest

      - name: Log in to Docker Registry
        run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin $DOCKER_HOST

      - name: Push Docker image to Registry
        run: docker push $DOCKER_HOST/your-docker-image-name:latest
